server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: mihao0804
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:Mappers/*.xml
  type-aliases-package: Mih.demo.Modules
  entity_package: Mih.demo.Modules
  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
