server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: mihao0804
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 0
        partitioner:
          class: Mih.demo.kafka.CustomizePartitioner
    consumer:
      properties:
        group:
          id: defaultConsumerGroup
        session:
          timeout:
            ms: 120000
        request:
          timeout:
            ms: 180000
      enable-auto-commit: true

      auto:
        commit:
          interval:
            ms: 1000
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:Mappers/*.xml
  type-aliases-package: Mih.demo.Modules
  entity_package: Mih.demo.Modules
  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
